### ISSUE TITLE
dev: implement view for listing players

### ISSUE THREAD

**Issue by MSNanda515** [CMPUT301W23T47/Canary#54]
Implement the view for listing all the players

**Comment by bc-davin** [comment]
Starting to think about this one.

**Comment by bc-davin** [comment]
Hi, I a little bit unsure about this one. Could we get on a call tomorrow during the lunch time to take about it a little bit more?

**Comment by MSNanda515** [comment]
Sure, we can talk after the spring planning meeting tomorrow
